version: '3.6'
# Development
services:
  web:
    environment:
    # Environment context
    - TYPO3_CONTEXT=Development
    # Database Credentials
    - TYPO3_DB_CONNECTIONS_DEFAULT_HOST=db
    - TYPO3_DB_CONNECTIONS_DEFAULT_PORT=3306
    - TYPO3_DB_CONNECTIONS_DEFAULT_USER=db
    - TYPO3_DB_CONNECTIONS_DEFAULT_PASS=db
    - TYPO3_DB_CONNECTIONS_DEFAULT_NAME=db
    # Mail
    - TYPO3_MAIL_TRANSPORT=smtp
    - TYPO3_MAIL_TRANSPORT_SMTP_SERVER=localhost:1025
    # System (replace if you like)
    - TYPO3_TRUSTED_HOST_PATTERN=$DDEV_HOSTNAME
    # Site (replace if you like)
    - TYPO3_SITENAME=${DDEV_SITENAME}
    # Install tool pass (double dollar to escape dollar symbol)
    #- TYPO3_INSTALLTOOLPASSWORD=